### ISSUE TITLE
Browser support?

### ISSUE THREAD

**Issue by aripalo** [QubitProducts/micro-amd#7]
First of all, nice looking library, but have to ask: What is the browser support of this library?

I noticed one of your dependencies [`fetch-js`](https://github.com/QubitProducts/fetch-js) says it: 
> Works in all good browsers and ie9+

… but then you also have commit https://github.com/QubitProducts/micro-amd/commit/2cd681be185aea7cac89ba7fa0ba1ea946887eea which states:
> Classic IE8.

IE9+ is more than enough for me, but generally speaking do you have a cross browser test suite or have you done manual tests? If so, it would probably be a good idea to notify the expected browser support status on the README.

**Comment by alanclarke** [comment]
Heya, thanks!

We are maintaining ie9+ support but it may work in ie8. It has a pretty good automated test suite which we run cross browser after any major change.
